import { Card } from "engine/CardPakTypes";

import { TILES } from "../Tiles";
import { DianXinDefault } from "../VisualDeck";

function getVisualsOf(hand: Card[]) {
  if (!Array.isArray(hand)) return [];
  return hand?.map((tile) => ({
    ...tile,
    visual: DianXinDefault.visualCards[tile.visualCardIndex],
  }));
}

export function getTileData(ids: string[]) {
  return getVisualsOf(
    ids
      .map((t) => TILES.find((tile) => tile.name === t))
      .filter((t) => !!t)
      .map((t) => ({ ...t, params: { ...t?.defaultParams } })) as Card[],
  );
}

//* For Mock Game

export const LEARN_PLAYERS = [
  {
    id: "tuzi",
    connected: true,
  },
  { id: "houzi", connected: true },
  { id: "laohu", connected: true },
  { id: "niu", connected: true },
];

export const LEARN_PLAYER_PARAMS = [
  {
    id: "tuzi",
    name: "Little Rabbit",
    closedHand: [
      {
        id: 97,
        name: "xifeng",
        params: { suit: "feng" },
        value: "west",
        visualCardIndex: 29,
      },
      {
        id: 44,
        name: "erwan",
        params: { suit: "wan" },
        value: 2,
        visualCardIndex: 1,
      },
      {
        id: 8,
        name: "jiutong",
        params: { suit: "tong" },
        value: 9,
        visualCardIndex: 26,
      },
      {
        id: 11,
        name: "sanwan",
        params: { suit: "wan" },
        value: 3,
        visualCardIndex: 2,
      },
      {
        id: 0,
        name: "yibing",
        params: { suit: "tong" },
        value: 1,
        visualCardIndex: 18,
      },
      {
        id: 122,
        name: "santiao",
        params: { suit: "tiao" },
        value: 3,
        visualCardIndex: 11,
      },
      {
        id: 127,
        name: "batiao",
        params: { suit: "tiao" },
        value: 8,
        visualCardIndex: 16,
      },
      {
        id: 25,
        name: "batiao",
        value: 8,
        params: { suit: "tiao" },
        visualCardIndex: 16,
      },
      {
        id: 28,
        name: "nanfeng",
        params: { suit: "feng" },
        value: "south",
        visualCardIndex: 28,
      },
      {
        id: 121,
        name: "liangtiao",
        params: { suit: "tiao" },
        value: 2,
        visualCardIndex: 10,
      },
      {
        id: 43,
        name: "yiwan",
        params: { suit: "wan" },
        value: 1,
        visualCardIndex: 0,
      },
      {
        id: 22,
        name: "wutiao",
        params: { suit: "tiao" },
        value: 5,
        visualCardIndex: 13,
      },
      {
        id: 23,
        name: "liutiao",
        params: { suit: "tiao" },
        value: 6,
        visualCardIndex: 14,
      },
    ],
    openHand: {},
    playedTiles: [],
    points: 0,
    skipped: false,
    winner: false,
    seat: 0,
  },
  {
    id: "houzi",
    name: "Monkey",
    closedHand: [
      {
        id: 110,
        name: "jiutong",
        value: 9,
        params: { suit: "tong" },
        visualCardIndex: 26,
      },
      {
        id: 14,
        name: "liuwan",
        params: { suit: "wan" },
        value: 6,
        visualCardIndex: 5,
      },
      {
        id: 54,
        name: "santiao",
        params: { suit: "tiao" },
        value: 3,
        visualCardIndex: 11,
      },
      {
        id: 86,
        name: "yaoji",
        params: { suit: "tiao" },
        value: 1,
        visualCardIndex: 9,
      },
      {
        id: 93,
        name: "batiao",
        params: { suit: "tiao" },
        value: 8,
        visualCardIndex: 16,
      },
      {
        id: 40,
        name: "qitong",
        params: { suit: "tong" },
        value: 7,
        visualCardIndex: 24,
      },
      {
        id: 7,
        name: "batong",
        params: { suit: "tong" },
        value: 8,
        visualCardIndex: 25,
      },
      {
        id: 102,
        name: "yibing",
        params: { suit: "tong" },
        value: 1,
        visualCardIndex: 18,
      },
      {
        id: 107,
        name: "liutong",
        params: { suit: "tong" },
        value: 6,
        visualCardIndex: 23,
      },
      {
        id: 74,
        name: "qitong",
        params: { suit: "tong" },
        value: 7,
        visualCardIndex: 24,
      },
      {
        id: 98,
        name: "beifeng",
        params: { suit: "feng" },
        value: "north",
        visualCardIndex: 30,
      },
      {
        id: 65,
        name: "hongzhong",
        params: { suit: "long" },
        value: "hongzhong",
        visualCardIndex: 31,
      },
      {
        id: 113,
        name: "sanwan",
        params: { suit: "wan" },
        value: 3,
        visualCardIndex: 2,
      },
    ],
    points: 0,
    skipped: false,
    winner: false,
    seat: 1,
  },
  {
    id: "laohu",
    name: "Tiger",
    closedHand: [
      {
        id: 16,
        name: "bawan",
        params: { suit: "wan" },
        value: 8,
        visualCardIndex: 7,
      },
      {
        id: 21,
        name: "sitiao",
        params: { suit: "tiao" },
        value: 4,
        visualCardIndex: 12,
      },
      {
        id: 75,
        name: "batong",
        params: { suit: "tong" },
        value: 8,
        visualCardIndex: 25,
      },
      {
        id: 30,
        name: "beifeng",
        params: { suit: "feng" },
        value: "north",
        visualCardIndex: 30,
      },
      {
        id: 69,
        name: "ertong",
        params: { suit: "tong" },
        value: 2,
        visualCardIndex: 19,
      },
      {
        id: 59,
        name: "batiao",
        params: { suit: "tiao" },
        value: 8,
        visualCardIndex: 16,
      },
      {
        id: 83,
        name: "qiwan",
        params: { suit: "wan" },
        value: 7,
        visualCardIndex: 6,
      },
      {
        id: 34,
        name: "yibing",
        params: { suit: "tong" },
        value: 1,
        visualCardIndex: 18,
      },
      {
        id: 114,
        name: "siwan",
        params: { suit: "wan" },
        value: 4,
        visualCardIndex: 3,
      },
      {
        id: 13,
        name: "wuwan",
        params: { suit: "wan" },
        value: 5,
        visualCardIndex: 4,
      },
      {
        id: 24,
        name: "qitiao",
        params: { suit: "tiao" },
        value: 7,
        visualCardIndex: 15,
      },
      {
        id: 123,
        name: "sitiao",
        params: { suit: "tiao" },
        value: 4,
        visualCardIndex: 12,
      },
      {
        id: 125,
        name: "liutiao",
        params: { suit: "tiao" },
        value: 6,
        visualCardIndex: 14,
      },
    ],
    points: 0,
    skipped: false,
    winner: false,
    seat: 2,
  },
  {
    id: "niu",
    name: "Ox",
    closedHand: [
      {
        id: 111,
        name: "yiwan",
        params: { suit: "wan" },
        value: 1,
        visualCardIndex: 0,
      },
      {
        id: 87,
        name: "liangtiao",
        params: { suit: "tiao" },
        value: 2,
        visualCardIndex: 10,
      },
      {
        id: 100,
        name: "facai",
        params: { suit: "long" },
        value: "facai",
        visualCardIndex: 32,
      },
      {
        id: 118,
        name: "bawan",
        params: { suit: "wan" },
        value: 8,
        visualCardIndex: 7,
      },
      {
        id: 63,
        name: "xifeng",
        params: { suit: "feng" },
        value: "west",
        visualCardIndex: 29,
      },
      {
        id: 61,
        name: "dongfeng",
        params: { suit: "feng" },
        value: "east",
        visualCardIndex: 27,
      },
      {
        id: 108,
        name: "qitong",
        params: { suit: "tong" },
        value: 7,
        visualCardIndex: 24,
      },
      {
        id: 10,
        name: "erwan",
        params: { suit: "wan" },
        value: 2,
        visualCardIndex: 1,
      },
      {
        id: 39,
        name: "liutong",
        params: { suit: "tong" },
        value: 6,
        visualCardIndex: 23,
      },
      {
        id: 131,
        name: "xifeng",
        params: { suit: "feng" },
        value: "west",
        visualCardIndex: 29,
      },
      {
        id: 1,
        name: "ertong",
        params: { suit: "tong" },
        value: 2,
        visualCardIndex: 19,
      },
      {
        id: 81,
        name: "wuwan",
        params: { suit: "wan" },
        value: 5,
        visualCardIndex: 4,
      },
      {
        id: 77,
        name: "yiwan",
        params: { suit: "wan" },
        value: 1,
        visualCardIndex: 0,
      },
    ],
    points: 0,
    skipped: false,
    winner: false,
    seat: 3,
  },
];

export const LEARN_GAME_PARAMS = {
  wall: [
    {
      id: 41,
      name: "batong",
      params: { suit: "tong" },
      value: 8,
      visualCardIndex: 25,
    },
    {
      id: 78,
      name: "erwan",
      params: { suit: "wan" },
      value: 2,
      visualCardIndex: 1,
    },
    {
      id: 95,
      name: "dongfeng",
      params: { suit: "feng" },
      value: "east",
      visualCardIndex: 27,
    },
    {
      id: 120,
      name: "yaoji",
      params: { suit: "tiao" },
      value: 1,
      visualCardIndex: 9,
    },
    {
      id: 6,
      name: "qitong",
      params: { suit: "tong" },
      value: 7,
      visualCardIndex: 24,
    },
    {
      id: 27,
      name: "dongfeng",
      params: { suit: "feng" },
      value: "east",
      visualCardIndex: 27,
    },
    {
      id: 101,
      name: "baiban",
      params: { suit: "long" },
      value: "baiban",
      visualCardIndex: 33,
    },
    {
      id: 18,
      name: "yaoji",
      params: { suit: "tiao" },
      value: 1,
      visualCardIndex: 9,
    },
    {
      id: 115,
      name: "wuwan",
      params: { suit: "wan" },
      value: 5,
      visualCardIndex: 4,
    },
    {
      id: 3,
      name: "sitong",
      params: { suit: "tong" },
      value: 4,
      visualCardIndex: 21,
    },
    {
      id: 17,
      name: "jiuwan",
      params: { suit: "wan" },
      value: 9,
      visualCardIndex: 8,
    },
    {
      id: 5,
      name: "liutong",
      params: { suit: "tong" },
      value: 6,
      visualCardIndex: 23,
    },
    {
      id: 94,
      name: "jiutiao",
      params: { suit: "tiao" },
      value: 9,
      visualCardIndex: 17,
    },
    {
      id: 4,
      name: "wutong",
      params: { suit: "tong" },
      value: 5,
      visualCardIndex: 22,
    },
    {
      id: 55,
      name: "sitiao",
      params: { suit: "tiao" },
      value: 4,
      visualCardIndex: 12,
    },
    {
      id: 85,
      name: "jiuwan",
      params: { suit: "wan" },
      value: 9,
      visualCardIndex: 8,
    },
    {
      id: 109,
      name: "batong",
      params: { suit: "tong" },
      value: 8,
      visualCardIndex: 25,
    },
    {
      id: 119,
      name: "jiuwan",
      params: { suit: "wan" },
      value: 9,
      visualCardIndex: 8,
    },
    {
      id: 49,
      name: "qiwan",
      params: { suit: "wan" },
      value: 7,
      visualCardIndex: 6,
    },
    {
      id: 82,
      name: "liuwan",
      params: { suit: "wan" },
      value: 6,
      visualCardIndex: 5,
    },
    {
      id: 52,
      name: "yaoji",
      params: { suit: "tiao" },
      value: 1,
      visualCardIndex: 9,
    },
    {
      id: 128,
      name: "jiutiao",
      params: { suit: "tiao" },
      value: 9,
      visualCardIndex: 17,
    },
    {
      id: 50,
      name: "bawan",
      params: { suit: "wan" },
      value: 8,
      visualCardIndex: 7,
    },
    {
      id: 36,
      name: "santong",
      params: { suit: "tong" },
      value: 3,
      visualCardIndex: 20,
    },
    {
      id: 96,
      name: "nanfeng",
      params: { suit: "feng" },
      value: "south",
      visualCardIndex: 28,
    },
    {
      id: 130,
      name: "nanfeng",
      params: { suit: "feng" },
      value: "south",
      visualCardIndex: 28,
    },
    {
      id: 103,
      name: "ertong",
      params: { suit: "tong" },
      value: 2,
      visualCardIndex: 19,
    },
    {
      id: 37,
      name: "sitong",
      params: { suit: "tong" },
      value: 4,
      visualCardIndex: 21,
    },
    {
      id: 89,
      name: "sitiao",
      params: { suit: "tiao" },
      value: 4,
      visualCardIndex: 12,
    },
    {
      id: 20,
      name: "santiao",
      params: { suit: "tiao" },
      value: 3,
      visualCardIndex: 11,
    },
    {
      id: 31,
      name: "hongzhong",
      params: { suit: "long" },
      value: "hongzhong",
      visualCardIndex: 31,
    },
    {
      id: 92,
      name: "qitiao",
      params: { suit: "tiao" },
      value: 7,
      visualCardIndex: 15,
    },
    {
      id: 88,
      name: "santiao",
      params: { suit: "tiao" },
      value: 3,
      visualCardIndex: 11,
    },
    {
      id: 132,
      name: "beifeng",
      params: { suit: "feng" },
      value: "north",
      visualCardIndex: 30,
    },
    {
      id: 58,
      name: "qitiao",
      params: { suit: "tiao" },
      value: 7,
      visualCardIndex: 15,
    },
    {
      id: 46,
      name: "siwan",
      params: { suit: "wan" },
      value: 4,
      visualCardIndex: 3,
    },
    {
      id: 126,
      name: "qitiao",
      params: { suit: "tiao" },
      value: 7,
      visualCardIndex: 15,
    },
    {
      id: 51,
      name: "jiuwan",
      params: { suit: "wan" },
      value: 9,
      visualCardIndex: 8,
    },
    {
      id: 134,
      name: "facai",
      params: { suit: "long" },
      value: "facai",
      visualCardIndex: 32,
    },
    {
      id: 47,
      name: "wuwan",
      params: { suit: "" },
      value: 5,
      visualCardIndex: 4,
    },
    {
      id: 48,
      name: "liuwan",
      params: { suit: "" },
      value: 6,
      visualCardIndex: 5,
    },
    {
      id: 80,
      name: "siwan",
      params: { suit: "" },
      value: 4,
      visualCardIndex: 3,
    },
    {
      id: 67,
      name: "baiban",
      params: { suit: "" },
      value: "baiban",
      visualCardIndex: 33,
    },
    {
      id: 38,
      name: "wutong",
      params: { suit: "" },
      value: 5,
      visualCardIndex: 22,
    },
    {
      id: 105,
      name: "sitong",
      params: { suit: "" },
      value: 4,
      visualCardIndex: 21,
    },
    {
      id: 135,
      name: "baiban",
      params: { suit: "" },
      value: "baiban",
      visualCardIndex: 33,
    },
    {
      id: 57,
      name: "liutiao",
      params: { suit: "tiao" },
      value: 6,
      visualCardIndex: 14,
    },
    {
      id: 64,
      name: "beifeng",
      params: { suit: "feng" },
      value: "north",
      visualCardIndex: 30,
    },
    {
      id: 53,
      name: "liangtiao",
      params: { suit: "tiao" },
      value: 2,
      visualCardIndex: 10,
    },
    {
      id: 112,
      name: "erwan",
      params: { suit: "wan" },
      value: 2,
      visualCardIndex: 1,
    },
    {
      id: 124,
      name: "wutiao",
      params: { suit: "tiao" },
      value: 5,
      visualCardIndex: 13,
    },
    {
      id: 70,
      name: "santong",
      params: { suit: "tong" },
      value: 3,
      visualCardIndex: 20,
    },
    {
      id: 33,
      name: "baiban",
      params: { suit: "long" },
      value: "baiban",
      visualCardIndex: 33,
    },
    {
      id: 91,
      name: "liutiao",
      params: { suit: "tiao" },
      value: 6,
      visualCardIndex: 14,
    },
    {
      id: 104,
      name: "santong",
      params: { suit: "tong" },
      value: 3,
      visualCardIndex: 20,
    },
    {
      id: 90,
      name: "wutiao",
      params: { suit: "tiao" },
      value: 5,
      visualCardIndex: 13,
    },
    {
      id: 9,
      name: "yiwan",
      params: { suit: "wan" },
      value: 1,
      visualCardIndex: 0,
    },
    {
      id: 32,
      name: "facai",
      params: { suit: "long" },
      value: "facai",
      visualCardIndex: 32,
    },
    {
      id: 26,
      name: "jiutiao",
      params: { suit: "tiao" },
      value: 9,
      visualCardIndex: 17,
    },
    {
      id: 62,
      name: "nanfeng",
      params: { suit: "feng" },
      value: "south",
      visualCardIndex: 28,
    },
    {
      id: 19,
      name: "liangtiao",
      params: { suit: "tiao" },
      value: 2,
      visualCardIndex: 10,
    },
    {
      id: 73,
      name: "liutong",
      params: { suit: "tong" },
      value: 6,
      visualCardIndex: 23,
    },
    {
      id: 106,
      name: "wutong",
      params: { suit: "tong" },
      value: 5,
      visualCardIndex: 22,
    },
    {
      id: 76,
      name: "jiutong",
      params: { suit: "tong" },
      value: 9,
      visualCardIndex: 26,
    },
    { id: 133, name: "hongzhong", value: "hongzhong", visualCardIndex: 31 },
    {
      id: 68,
      name: "yibing",
      params: { suit: "tong" },
      value: 1,
      visualCardIndex: 18,
    },
    {
      id: 84,
      name: "bawan",
      params: { suit: "wan" },
      value: 8,
      visualCardIndex: 7,
    },
    {
      id: 29,
      name: "xifeng",
      params: { suit: "feng" },
      value: "west",
      visualCardIndex: 29,
    },
    {
      id: 71,
      name: "sitong",
      params: { suit: "tong" },
      value: 4,
      visualCardIndex: 21,
    },
    {
      id: 66,
      name: "facai",
      params: { suit: "long" },
      value: "facai",
      visualCardIndex: 32,
    },
  ],
  deadWall: [
    {
      id: 35,
      name: "ertong",
      params: { suit: "tong" },
      value: 2,
      visualCardIndex: 19,
    },
    {
      id: 72,
      name: "wutong",
      params: { suit: "tong" },
      value: 5,
      visualCardIndex: 22,
    },
    {
      id: 15,
      name: "qiwan",
      params: { suit: "wan" },
      value: 7,
      visualCardIndex: 6,
    },
    {
      id: 2,
      name: "santong",
      params: { suit: "tong" },
      value: 3,
      visualCardIndex: 20,
    },
    {
      id: 117,
      name: "qiwan",
      params: { suit: "wan" },
      value: 7,
      visualCardIndex: 6,
    },
    {
      id: 99,
      name: "hongzhong",
      params: { suit: "feng" },
      value: "hongzhong",
      visualCardIndex: 31,
    },
    {
      id: 60,
      name: "jiutiao",
      params: { suit: "tiao" },
      value: 9,
      visualCardIndex: 17,
    },
    {
      id: 45,
      name: "sanwan",
      params: { suit: "wan" },
      value: 3,
      visualCardIndex: 2,
    },
    {
      id: 56,
      name: "wutiao",
      params: { suit: "tiao" },
      value: 5,
      visualCardIndex: 13,
    },
    {
      id: 12,
      name: "siwan",
      params: { suit: "wan" },
      value: 4,
      visualCardIndex: 3,
    },
    {
      id: 79,
      name: "sanwan",
      params: { suit: "wan" },
      value: 3,
      visualCardIndex: 2,
    },
    {
      id: 129,
      name: "dongfeng",
      params: { suit: "feng" },
      value: "east",
      visualCardIndex: 27,
    },
    {
      id: 116,
      name: "liuwan",
      params: { suit: "wan" },
      value: 6,
      visualCardIndex: 5,
    },
    {
      id: 42,
      name: "jiutong",
      params: { suit: "tong" },
      value: 9,
      visualCardIndex: 26,
    },
  ],
  lastPlay: null,
  seatTurn: 0,
};
